"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mapErrorToTRPC = exports.ERROR_CODES = exports.ExternalServiceError = exports.InternalError = exports.SystemError = exports.AuthorizationError = exports.StateError = exports.ConflictError = exports.ValidationError = exports.NotFoundError = exports.BusinessError = exports.AppError = void 0;
var base_errors_1 = require("./base.errors");
Object.defineProperty(exports, "AppError", { enumerable: true, get: function () { return base_errors_1.AppError; } });
var business_errors_1 = require("./business.errors");
Object.defineProperty(exports, "BusinessError", { enumerable: true, get: function () { return business_errors_1.BusinessError; } });
Object.defineProperty(exports, "NotFoundError", { enumerable: true, get: function () { return business_errors_1.NotFoundError; } });
Object.defineProperty(exports, "ValidationError", { enumerable: true, get: function () { return business_errors_1.ValidationError; } });
Object.defineProperty(exports, "ConflictError", { enumerable: true, get: function () { return business_errors_1.ConflictError; } });
Object.defineProperty(exports, "StateError", { enumerable: true, get: function () { return business_errors_1.StateError; } });
Object.defineProperty(exports, "AuthorizationError", { enumerable: true, get: function () { return business_errors_1.AuthorizationError; } });
var system_errors_1 = require("./system.errors");
Object.defineProperty(exports, "SystemError", { enumerable: true, get: function () { return system_errors_1.SystemError; } });
Object.defineProperty(exports, "InternalError", { enumerable: true, get: function () { return system_errors_1.InternalError; } });
Object.defineProperty(exports, "ExternalServiceError", { enumerable: true, get: function () { return system_errors_1.ExternalServiceError; } });
var error_codes_1 = require("./error-codes");
Object.defineProperty(exports, "ERROR_CODES", { enumerable: true, get: function () { return error_codes_1.ERROR_CODES; } });
var trpc_mapper_1 = require("./trpc-mapper");
Object.defineProperty(exports, "mapErrorToTRPC", { enumerable: true, get: function () { return trpc_mapper_1.mapErrorToTRPC; } });
