# Generated by Cove Deploy Toolkit
FROM nginx:alpine

# Copy build output
COPY code/cloud/frontend/dist /usr/share/nginx/html

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]