# Generated by Cove Deploy Toolkit
FROM node:20-alpine

WORKDIR /app

# Copy build output
COPY code/cloud/backend/dist ./dist
COPY code/cloud/backend/package.json ./
COPY code/cloud/backend/prisma ./prisma

# Install production dependencies
RUN npm install --production

# Generate Prisma client
RUN npx prisma generate

# Expose port
EXPOSE 3002

# Start command
CMD ["node","dist/bundle.js"]