/**
 * Centralized error code registry.
 * All error codes must be unique and follow the ENTITY_CONDITION format.
 */
export const ERROR_CODES = {
  // Agent errors
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  AGENT_NOT_AVAILABLE: 'AGENT_NOT_AVAILABLE',
  AGENT_IN_USE: 'AGENT_IN_USE',
  AGENT_RESPONSE_GENERATION_FAILED: 'AGENT_RESPONSE_GENERATION_FAILED',

  // Channel errors
  CHANNEL_NOT_FOUND: 'CHANNEL_NOT_FOUND',
  CHANNEL_NOT_ACTIVE: 'CHANNEL_NOT_ACTIVE',
  CHANNEL_NOT_ARCHIVED: 'CHANNEL_NOT_ARCHIVED',
  MEMBER_NOT_IN_CHANNEL: 'MEMBER_NOT_IN_CHANNEL',

  // Message errors
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  SENDER_NOT_IN_CHANNEL: 'SENDER_NOT_IN_CHANNEL',
  MESSAGE_DELETION_UNAUTHORIZED: 'MESSAGE_DELETION_UNAUTHORIZED',
  MESSAGE_EDIT_UNAUTHORIZED: 'MESSAGE_EDIT_UNAUTHORIZED',
  SEND_MESSAGE_DENIED: 'SEND_MESSAGE_DENIED',

  // Task errors
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_NOT_ASSIGNABLE: 'TASK_NOT_ASSIGNABLE',
  TASK_NOT_DELETABLE: 'TASK_NOT_DELETABLE',

  // Member errors
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_NOT_FOUND_IN_CHANNEL: 'MEMBER_NOT_FOUND_IN_CHANNEL',
  MEMBER_ALREADY_IN_CHANNEL: 'MEMBER_ALREADY_IN_CHANNEL',
  CHANNEL_NOT_FOUND_FOR_MEMBER: 'CHANNEL_NOT_FOUND_FOR_MEMBER',
  USER_NOT_FOUND_FOR_MEMBER: 'USER_NOT_FOUND_FOR_MEMBER',

  // User errors
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

  // Server errors
  SERVER_NOT_FOUND: 'SERVER_NOT_FOUND',
  SERVER_NAME_EXISTS: 'SERVER_NAME_EXISTS',
  SERVER_NOT_ACTIVE: 'SERVER_NOT_ACTIVE',
  SERVER_ALREADY_ARCHIVED: 'SERVER_ALREADY_ARCHIVED',
  SERVER_NOT_ARCHIVED: 'SERVER_NOT_ARCHIVED',
  UNAUTHORIZED_SERVER_ACCESS: 'UNAUTHORIZED_SERVER_ACCESS',

  // Device errors
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_NAME_EXISTS: 'DEVICE_NAME_EXISTS',
  DEVICE_NOT_ACTIVE: 'DEVICE_NOT_ACTIVE',
  DEVICE_ALREADY_REVOKED: 'DEVICE_ALREADY_REVOKED',
  DEVICE_NOT_REVOKED: 'DEVICE_NOT_REVOKED',
  UNAUTHORIZED_DEVICE_ACCESS: 'UNAUTHORIZED_DEVICE_ACCESS',

  // Project errors
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_NOT_ARCHIVED: 'PROJECT_NOT_ARCHIVED',

  // Thread errors
  ROOT_MESSAGE_NOT_FOUND: 'ROOT_MESSAGE_NOT_FOUND',
  NESTED_THREAD_NOT_ALLOWED: 'NESTED_THREAD_NOT_ALLOWED',

  // Workflow errors
  WORKFLOW_NOT_FOUND: 'WORKFLOW_NOT_FOUND',
  WORKFLOW_NOT_DELETABLE: 'WORKFLOW_NOT_DELETABLE',
  WORKFLOW_STEPS_INVALID: 'WORKFLOW_STEPS_INVALID',

  // Infrastructure errors - LLM
  LLM_PROVIDER_ERROR: 'LLM_PROVIDER_ERROR',
  LLM_INVALID_RESPONSE: 'LLM_INVALID_RESPONSE',

  // Infrastructure errors - Storage
  STORAGE_ERROR: 'STORAGE_ERROR',
  STORAGE_FILE_NOT_FOUND: 'STORAGE_FILE_NOT_FOUND',
  STORAGE_PATH_RESOLUTION_ERROR: 'STORAGE_PATH_RESOLUTION_ERROR',

  // Infrastructure errors - Repository
  REPOSITORY_ERROR: 'REPOSITORY_ERROR',
  REPOSITORY_ENTITY_NOT_FOUND: 'REPOSITORY_ENTITY_NOT_FOUND',
  REPOSITORY_SAVE_ERROR: 'REPOSITORY_SAVE_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',

  // Generic errors for testing
  INVALID_INPUT: 'INVALID_INPUT',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

// Export as ErrorCode for backward compatibility
export const ErrorCode = ERROR_CODES;
